# Generated by Django 4.2.24 on 2026-02-02 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('prospect_name', models.CharField(blank=True, max_length=200)),
                ('prospect_company', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, choices=[('cybersecurite', 'Cybersécurité / OT-IT'), ('juridique', 'Juridique / Cabinets avocats'), ('industrie', 'Industrie'), ('low-tech', 'Low tech / Sans tech'), ('autre', 'Autre')], default='autre', max_length=40)),
                ('category', models.CharField(blank=True, choices=[('relance-evenement', 'Relance événement'), ('proposition', 'Proposition / Mission'), ('lead-magnet', 'Lead magnet'), ('autre', 'Autre')], default='autre', max_length=40)),
                ('template_key', models.CharField(default='default', max_length=80)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Landing page',
                'verbose_name_plural': 'Landing pages',
                'ordering': ['-created_at'],
            },
        ),
    ]
