# Generated by Django 4.2.24 on 2026-02-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0001_add_sector_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='deploy_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
