# Generated by Django 5.2.11 on 2026-02-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0002_add_deploy_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='category',
            field=models.CharField(blank=True, choices=[('relance-evenement', 'Relance événement'), ('proposition', 'Proposition / Mission'), ('lead-magnet', 'Lead magnet'), ('lowtech', 'Low tech / Sans tech'), ('autre', 'Autre')], default='autre', max_length=40),
        ),
    ]
